
GET http://localhost:3003/api/users
### ovo dole je registracioni request
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"Nick",
    "name":"Popideck",
    "password":"123"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
     "username":"Teril Peston",
    "password":"fuckniggersandblacks"
}
###
POST http://localhost:3003/api/blogs/645fce01708bbb71bb1e0217/comments
Content-Type: application/json

{
    "reply":"nebesa kazuju slavu boziju nebeski svod glasi delo ruku njegovih"
}
